apiVersion: v1
kind: Service
metadata:
  name: cv-site
  namespace: cv-stack
  labels:
    app: cv-site
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: cv-site
---
apiVersion: v1
kind: Service
metadata:
  name: linktree-site
  namespace: cv-stack
  labels:
    app: linktree-site
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: linktree-site
---
apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: cv-stack
  labels:
    app: traefik
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: web
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: admin
  selector:
    app: traefik
